<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-N20DUSAV" ignored="0" name="Automated tests" tests="2" failures="1" timestamp="21 Mar 2018 00:29:42 GMT" time="25.62" errors="0">
  <testcase name="runScenario" time="14.788" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="10.6" classname="cucumber.api.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertFalse(Assert.java:65)
at org.testng.Assert.assertFalse(Assert.java:75)
at com.app.step_definitions.UITestsStepDefs.modules_should_be_displayed(UITestsStepDefs.java:39)
at âœ½.Modules should be displayed(src/test/resources/com/app/features/userinterfaceTests.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Automated tests -->
